# Generated by Django 4.0.2 on 2022-02-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_basepicture_author_basepicture_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepicture',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
