# Generated by Django 3.2 on 2022-02-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_basepicture_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepicture',
            name='enl_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
