# Generated by Django 3.2 on 2022-02-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_basepicture_enl_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPaintingPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painter', models.CharField(max_length=50)),
                ('base_picture_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.basepicture')),
            ],
            options={
                'db_table': 'myarticle',
            },
        ),
    ]
